### ISSUE TITLE
setup.py causes pip 25.1 deprecation warning

### ISSUE THREAD

**Issue by eliteprox** [yondonfu/comfystream#35]
When running `pip install -e .` the following deprecation notice shows:
```
Installing collected packages: comfystream
  Attempting uninstall: comfystream
    Found existing installation: comfystream 0.1.0
    Uninstalling comfystream-0.1.0:
      Successfully uninstalled comfystream-0.1.0
  DEPRECATION: Legacy editable install of comfystream==0.1.0 from file:///comfystream (setup.py develop) is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
```

We can resolve this by migrating to `pyproject.toml` which replaces setup.py. Adding example for later:

```toml pyproject.toml
[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comfystream"
version = "0.1.0"
dependencies = [
    "asyncio",
    "opentelemetry-distro==0.48b0",
    "opentelemetry-exporter-otlp==1.27.0",
    "opentelemetry-propagator-jaeger==1.27.0",
    "opentelemetry-instrumentation==0.48b0",
    "opentelemetry-util-http==0.48b0",
    "opentelemetry-instrumentation-aio-pika==0.48b0",
    "opentelemetry-instrumentation-requests==0.48b0",
    "opentelemetry-semantic-conventions==0.48b0"
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/yondonfu/comfystream"

[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
```

This installs successfully without warning. For backwards compatibility, `setup.py` should be 
```
from setuptools import setup

# Minimal setup.py that defers to pyproject.toml
setup()
```
